In [ ]:
import numpy as np

Arrays em NumPy são 100x mais rápidos do que em listas, em contra partida só armazenam valores do mesmo tipo


Toda e qualquer alteração no array mesmo que em pedaços em outras variaveis será modificada no array original

In [ ]:
arr = np.arange(1000)
arr = arr * 2 
#print(arr)

Arrays 1D = [1, 2, 3]

Arrays 2D = [[1, 2, 3], [1, 2, 3]]

Arrays 3D = [[[1, 2, 3], [1, 2, 3]], [[1, 2, 3]], [[1,2, 3]], [[1,2,3], [1,2,3]]]

In [ ]:
#O atributo ndim nos fornece o número de dimensões do array
arr.ndim

1

In [ ]:
# O atributo shape nos diz quantos elementos temos em cada dimensão (valor de itens na dimensão 1, ..., valor de items na dimensão n - 1)
arr.shape

(1000,)

In [ ]:
#Lista p array:
arr2 = np.array([[1, 2, 3], [1, 2, 3]])
print(type(arr2))

<class 'numpy.ndarray'>


Gerando arrays de zeros

In [ ]:
# somente uma dimensão:
arrays_zero = np.zeros(10)

# uma ou mais demnsões:
arrays_zero2 = np.zeros((2, 10))

print(f'Only one dimension:  {arrays_zero}')
print(f'More dimensions: \n{arrays_zero2}')

Only one dimension:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
More dimensions: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Gerando arrays de um: (segue a mesma do logica do array de zero)

In [ ]:
uns = np.ones((2, 10))
print(uns)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Arrays de intervalos:

In [ ]:
intervalo_array = np.arange(10)
print(intervalo_array)

[0 1 2 3 4 5 6 7 8 9]


Visualização com fatiamento:

In [ ]:
array3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(array3[0:2])

[0 1]


In [ ]:
#substituição por intervalos

array3[0:2] = 11

print(array3)

[11 11  2  3  4  5  6  7  8  9 10]


In [ ]:
array_mul = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_mul)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Indexação de valores:

In [ ]:
new_a = np.array([[ 0.08332437,  0.74508302,  0.29377823, -0.40309144],
       [-0.00657249, -0.37183682,  1.65978568,  0.24354861],
       [ 0.92646306, -1.60207788, -0.70337059,  0.04696397],
       [ 0.64716676, -0.63640023, -0.83317346, -1.1008962 ],
       [ 0.37581831, -1.20021293,  0.73862489, -0.76597305],
       [-1.49527206,  0.72298234,  1.59186498, -1.04811938],
       [ 0.36767802, -0.43538573, -0.87275053, -0.15102263]])

print(new_a)

[[ 0.08332437  0.74508302  0.29377823 -0.40309144]
 [-0.00657249 -0.37183682  1.65978568  0.24354861]
 [ 0.92646306 -1.60207788 -0.70337059  0.04696397]
 [ 0.64716676 -0.63640023 -0.83317346 -1.1008962 ]
 [ 0.37581831 -1.20021293  0.73862489 -0.76597305]
 [-1.49527206  0.72298234  1.59186498 -1.04811938]
 [ 0.36767802 -0.43538573 -0.87275053 -0.15102263]]


In [ ]:
print((new_a> 0) & (new_a<1))

[[ True  True  True False]
 [False False False  True]
 [ True False False  True]
 [ True False False False]
 [ True False  True False]
 [False  True False False]
 [ True False False False]]


In [ ]:
new_a[new_a < 0] = 0

print(new_a)

[[0.08332437 0.74508302 0.29377823 0.        ]
 [0.         0.         1.65978568 0.24354861]
 [0.92646306 0.         0.         0.04696397]
 [0.64716676 0.         0.         0.        ]
 [0.37581831 0.         0.73862489 0.        ]
 [0.         0.72298234 1.59186498 0.        ]
 [0.36767802 0.         0.         0.        ]]


transformamos array para uma matriz:

In [ ]:
n_a = np.arange(20).reshape((4,5))

print(n_a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Matriz tranposta:

In [ ]:
print(n_a.T)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Soma da matiz com a tranposta da mesma:

In [ ]:
print(np.dot(n_a.T, n_a))

[[350 380 410 440 470]
 [380 414 448 482 516]
 [410 448 486 524 562]
 [440 482 524 566 608]
 [470 516 562 608 654]]


Incompleto: organização da matriz, substituição, estrutura consicional para substituição, funções para estatistica, ...